{"name": "Проверка ошибки при попытке удаления курьера с несуществующим id", "status": "passed", "steps": [{"name": "Удаление курьера", "status": "passed", "parameters": [{"name": "courier_id", "value": "'234563256'"}], "start": 1744280278168, "stop": 1744280278231}], "start": 1744280278168, "stop": 1744280278231, "uuid": "26f0573b-4075-4839-b7c5-6edcb3df0298", "historyId": "5b467e2b3a88d96991fac68accedff2b", "testCaseId": "5b467e2b3a88d96991fac68accedff2b", "fullName": "tests.tests_couriers.test_courier_delete.TestCourierDelete#test_courier_delete_error_with_empty", "labels": [{"name": "parentSuite", "value": "tests.tests_couriers"}, {"name": "suite", "value": "test_courier_delete"}, {"name": "subSuite", "value": "TestCourierDelete"}, {"name": "host", "value": "Evgeny"}, {"name": "thread", "value": "16148-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.tests_couriers.test_courier_delete"}]}